services:
  backend:
    container_name: backend
    image: yopepsi/tvote-backend:latest
    env_file:
      - .env
    command: >
      sh -c "alembic upgrade head ; uvicorn app.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - postgres
      - redis
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - ./nginx/prod/data/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/prod/cert/vote-ist-ru.crt:/etc/ssl/ca.crt
      - ./nginx/prod/cert/vote-ist-ru.key:/etc/ssl/ca.key
      - ./frontend/build/:/usr/src/tVote/frontend/build/
    depends_on:
      - backend
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - 5432:5432  # для доступа из pgAdmin
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  postgres-db: