"""add profburo votes

Revision ID: 2d03ac6a8271
Revises: e9a7c8c4b367
Create Date: 2024-09-18 20:36:24.451865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d03ac6a8271'
down_revision: Union[str, None] = 'e9a7c8c4b367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProfburoVotes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ProfburoVotes')
    # ### end Alembic commands ###
