"""add profburo members

Revision ID: d26d321737ae
Revises: ee275ab37e62
Create Date: 2024-09-16 13:31:58.148104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26d321737ae'
down_revision: Union[str, None] = 'ee275ab37e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProfburoMembers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('photo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('Candidates', 'faculty')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Candidates', sa.Column('faculty', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('ProfburoMembers')
    # ### end Alembic commands ###
