name: build & deploy of tvote

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    environment:
      name: test
    env:
      database_hostname: ${{secrets.database_hostname}}
      database_port: ${{secrets.database_port}}
      database_password: ${{secrets.database_password}}
      database_name: ${{secrets.database_name}}
      database_username: ${{secrets.database_username}}
      secret_key: ${{secrets.secret_key}}
      algorithm: ${{secrets.algorithm}}
      access_token_expire_minutes: ${{secrets.access_token_expire_minutes}}

    services:
      postgres:
        image: postgres
        env:
          postgres_password: ${{secrets.database_password}}
          postgres_db: ${{secrets.database_name}}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: checkout our code
        uses: actions/checkout@v4.1.1
      - name: setup python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.12'
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install requirements.txt
        run: pip install -r requirements.txt
      - name: start tests
        run: |
          pip install pytest
          pytest
      - name: login to docker hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.docker_hub_username }}
          password: ${{ secrets.docker_hub_token }}
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.10.0
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.docker_hub_username }}/lovely-you-api:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  deploy:
    runs-on: ubuntu-20.04
    needs: [build]
    environment:
      name: production
    steps:
      - name: checkout our code
        uses: actions/checkout@v4.1.1
#      - name: deploy to ubuntu
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{secrets.prod_host}}
#          username: ${{secrets.prod_username}}
#          password: ${{secrets.prod_password}}
#          script: |
#            cd app/src
#            git pull
#            echo ${{secrets.prod_password}} | sudo -s systemctl restart api
      - name: composing docker images
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.prod_host}}
          username: ${{secrets.prod_username}}
          password: ${{secrets.prod_password}}
          script: |
            cd app/src
            git pull
#            docker compose -f docker-compose-prod.yml up -d

          # remember that .env file must exist in ./


