name: build & deploy of tvote

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-20.04
    environment:
      name: test
    env:
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      OWNER_EMAIL: ${{secrets.OWNER_EMAIL}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
      GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
      GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
      MS_API_KEY: ${{secrets.MS_API_KEY}}
      MS_DOMAIN: ${{secrets.MS_DOMAIN}}


    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.DATABASE_NAME}}-test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379

    steps:
      #  --------------- Тестирование на машине GitHub ---------------
      - name: checkout our code
        uses: actions/checkout@v4.1.1
      - name: setup python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.12'
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: install requirements.txt
        run: pip install -r requirements.txt
      - name: Start tests
        run: |
          pip install pytest
          pytest tests
      #  --------------- Билд Docker Image & Залив на Docker Hub ---------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.docker_hub_username }}
          password: ${{ secrets.docker_hub_token }}
      - name: Set Up Docker BuildX
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.10.0
      - name: List files
        run: ls -la
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.docker_hub_username }}/tvote:latest



  deploy:
    runs-on: ubuntu
    needs: [build]
    environment:
      name: production
    steps:
      - name: checkout our code
        uses: actions/checkout@v4.1.1
      - name: deploy to ubuntu vps
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.prod_host}}
          username: ${{secrets.prod_username}}
          password: ${{secrets.prod_password}}
          script: |
            cd app/src/tVote
            git pull
            docker-compose -f docker-compose-prod.yml pull
            docker compose -f docker-compose-prod.yml up -d

          # .env уже должен лежать на серваке


